#!/bin/bash

# The script filters mirror servers according to the selected country and sorts them by speed

COUNTRY=Czechia

if [[ $# -eq 1 ]]; then
  COUNTRY=$1
fi

pacman -Syyy
sleep 1
pacman -S reflector
sleep1
reflector -c $COUNTRY -a 6 --sort rate --save /etc/pacman.d/mirrorlist
sleep 1
pacman -Syyy
