#!/bin/bash

echo "---------------------------------------------"
echo "OPTIMIZING MIRRORLIST"
echo "---------------------------------------------"

# The script filters mirror servers according to the selected country and sorts them by speed

COUNTRY=Germany

if [[ $# -eq 1 ]]; then
  COUNTRY=$1
fi

sudo pacman -Syyy
sleep 1
sudo pacman -S reflector
sleep1
sudo reflector -c $COUNTRY -a 6 --sort rate --save /etc/pacman.d/mirrorlist
sleep 1
sudo pacman -Syyy
