#!/bin/bash

# kill previous gphoto instances if any
kill -9 $(awk '{print $2}' <(ps aux | grep gphoto))

# start streaming via gphoto
gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0
