#!/bin/bash

# Automatically create system snapshot
sh snapper-snap root SystemUpdate

echo "---------------------------------------------"
echo "PACMAN UPDATE"
echo "---------------------------------------------"

# Update pacman
sudo pacman -Syyu

echo "---------------------------------------------"
echo "AUR UPDATE"
echo "---------------------------------------------"

# Update AUR
yay -Syyu
