#!/bin/bash

sh snapper-snap root SystemUpdate

echo "---------------------------------------------"
echo "PACMAN UPDATE"
echo "---------------------------------------------"

pacman -Syu

echo "---------------------------------------------"
echo "AUR UPDATE"
echo "---------------------------------------------"

yay -Syu
