#!/bin/bash

# Automatically create system snapshot
sudo sh snapper-snap root SystemUpdate

echo "---------------------------------------------"
echo "PACMAN UPDATE"
echo "---------------------------------------------"

# Update pacman
sudo pacman -Syyu

echo "---------------------------------------------"
echo "AUR UPDATE"
echo "---------------------------------------------"

# Update yay
yay -Syu
