#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "---------------------------------------------"
echo "SERVICES"
echo "---------------------------------------------"

sudo systemctl --failed

echo "---------------------------------------------"
echo "JOURNAL"
echo "---------------------------------------------"

sudo journalctl -p 3 -xb
