#!/bin/bash

flatpak install flathub com.slack.Slack
flatpak install flathub com.spotify.Client
flatpak install flathub com.valvesoftware.Steam
flatpak install flathub com.discordapp.Discord
flatpak install flathub com.obsproject.Studio
flatpak install flathub org.blender.Blender
flatpak install flathub com.axosoft.GitKraken
flatpak install flathub com.dropbox.Client
